export const githubUrl = 'https://github.com/adillpickles/ClipPress/';
export const homepageUrl = 'https://github.com/adillpickles/ClipPress/';
export const getReleaseUrl = (version: string) => `https://github.com/adillpickles/ClipPress/releases/tag/v${version}`;
export const compareReleasesUrl = (fromVersion: string, toVersion: string) => `https://github.com/adillpickles/ClipPress/compare/v${fromVersion}...v${toVersion}`;
export const licensesUrl = 'https://losslesscut.mifi.no/licenses.txt';
export const thanksUrl = 'https://mifi.no/thanks';
export const discussionsUrl = 'https://github.com/adillpickles/ClipPress/discussions';
export const usageUrl = 'https://github.com/adillpickles/ClipPress#readme';
export const faqUrl = 'https://github.com/adillpickles/ClipPress#readme';
export const featureRequestUrl = 'https://github.com/adillpickles/ClipPress/issues/new';
export const publicBugReportUrl = 'https://github.com/adillpickles/ClipPress/issues/new';
export const troubleshootingUrl = 'https://github.com/adillpickles/ClipPress/issues';
export const exportedFileNameTemplateHelpUrl = 'https://github.com/adillpickles/ClipPress#readme';
export const selectSegmentByExpressionHelpUrl = 'https://github.com/adillpickles/ClipPress#readme';
export const editSegmentByExpressionHelpUrl = 'https://github.com/adillpickles/ClipPress#readme';
export const changeEnabledStreamsExpressionHelpUrl = 'https://github.com/adillpickles/ClipPress#readme';
